# Default values for dask.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# nameOverride: dask

scheduler:
  name: scheduler
  image: "daskdev/dask"
  imageTag: "latest"
  replicas: 1
  component: "dask-scheduler"
  serviceType: "LoadBalancer"
  servicePort: 8786
  containerPort: 8786
  resources: {}
  condaPackages: >-
  pipPackages: >-

  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 500m
  #   memory: 512Mi

webUI:
  name: webui
  servicePort: 80
  containerPort: 8787

worker:
  name: worker
  image: "daskdev/dask"
  imageTag: "latest"
  replicas: 3
  component: "dask-worker"
  containerPort: 8081
  resources: {}
  condaPackages: >-
    # numba
    # xarray
  pipPackages: >-
    # gcsfs
    # s3fs
    # adlfs
    # dask-ml

  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 500m
  #   memory: 512Mi

jupyter:
  enabled: false
